language: node_js
# node_js: 11.10.0
node_js: lts/*
dist: trusty
sudo: required

git:
  depth: 999

# before_install:
#   - npm install -g yarn

install:
  - yarn install

script:
  - scripts/prebuild.sh
  - yarn build

before_deploy:
  - cp package.json dist/
  - cd dist

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
