language: node_js
node_js: stable
dist: trusty
sudo: required

install:
  - yarn install

script:
  - scripts/prebuild.sh
  - yarn build

deploy:
  provider: azure_web_apps
  skip_cleanup: false
  verbose: true
