language: node_js
node_js: stable
dist: trusty
sudo: required

git:
  depth: 999

install:
  - yarn install

script:
  - scripts/prebuild.sh
  - yarn build

before_deploy:
  - cp package.json dist/
  - cd dist

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
